# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

executors:
  clojure:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0

orbs:
  gradle: circleci/gradle@3.0.0

parameters:
  run-slt:
    type: boolean
    default: false

workflows:
  build:
    when:
      not: << pipeline.parameters.run-slt >>
    jobs:
      - gradle/test:
          cache_key: v2
          deps_checksum_file: build.gradle.kts
          executor: clojure
